# conda 开发环境：conda env create -f environment.yml && conda activate netspy
# 之后 pre-commit install
name: netspy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - -e .[dev]
